config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'static_pages#landing'
    devise_for :users, :controllers => { registrations: 'users/registrations' }
    # Allows us to use link_to for session destroy
    devise_scope :user do
      get "/users/sign_out", as: "sign_out", to: "devise/sessions#destroy"
    end
    resources :stores, only: %i[index show]
    resources :locations, only: %i[index create]
    resource :shopping_cart, only: %i[show] do
      post 'add_food/:food_id(/:quantity)', action: :add_food, as: :add_food_to
      get 'checkout', action: :checkout, as: :checkout
      post 'remove_food/:food_id', action: :remove_food, as: :remove_food_from
    end
    resources :orders, only: %i[show] do
      post 'payment', action: :payment, as: :payment
    end
    # stripe webhooks
    mount StripeEvent::Engine, at: '/webhooks'
    post '/webhooks/stripe', to: 'webhooks#stripe'

    get "/success" => "static_pages#success"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    before_action :authenticate_user!, only: %i[success]
    before_action :unset_cart, only: %i[success]
    
    def landing
        render :landing
    end

    def success
        render :success
    end

    private
    def unset_cart
        session[:shopping_cart_id] = nil
    end
end

app/views/static_pages/landing.html.erb
<header>
  <div class="d-flex flex-column-reverse flex-md-row align-items-center justify-content-center p-4">
    <div class="d-flex flex-column justify-content-center align-items-center m-4 w-75 w-md-25">
      <h1 class="fw-bolder text-dark text-md-start"><%= t('landing_page.make_order') %></h1>
      <h5 class="text-secondary text-md-start text"><%= t('landing_page.make_order_subtext') %></h5>
      <button class="btn btn-success p-2 w-50 w-lg-100 m-4 text-nowrap fw-bolder" type="button" >
        <% if current_user %>
          <% if current_user.location_id.present? %>
            <%= link_to t('landing_page.order_now'), stores_path, class: "nav-link active" %>
          <% else %>
            <%= link_to t('landing_page.order_now'), locations_path, class: "nav-link active" %>
          <% end %>
        <% else %>
          <%= link_to t('landing_page.order_now'), new_session_path(User), class:"nav-link active" %>
        <% end %>
      </button>
    </div>
    <%# -------Imagen del header responsive%>
    <div class="container-fluid d-flex justify-content-center p-md-4">
      <img src="assets/pizza.jpg" class="w-100 w-md-25 h-md-25" id="img">
    </div>
  </div>
</header>
<section>
  <%# -------ONBOARDING DE COMO USAR LA WEB%>
  <div class="d-flex align-items-center text-center justify-content-center">
    <h3 class="fw-semibold text fs-6 mb-4 align-self-center" style="color:#11A87B;padding: 10px;"><%= t('landing_page.onboarding.onboard_1') %></h3>
  </div>
  <div class="d-flex flex-column flex-md-row" style="margin-left:2rem; margin-bottom:6rem">
    <img src="/assets/deliver.png" style="max-width: 600px;border-radius: 10px;">
    <div class="d-flex flex-wrap flex-column" style="margin-left:4px">
      <p class="fw-semibold"><i class="bi bi-check2-circle fw-bold fs-2" style="color:#0081A7;margin-right: 6px;"></i><%= t('landing_page.onboarding.onboard_2') %></p>
      <p class="fw-semibold"><i class="bi bi-check2-circle fw-bold fs-2" style="color:#0081A7;margin-right: 6px;"></i><%= t('landing_page.onboarding.onboard_3') %></p>
      <p class="fw-semibold"><i class="bi bi-check2-circle fw-bold fs-2" style="color:#0081A7;margin-right: 6px;"></i><%= t('landing_page.onboarding.onboard_4') %></p>
      <p class="fw-semibold"><i class="bi bi-check2-circle fw-bold fs-2" style="color:#0081A7;margin-right: 6px;"></i><%= t('landing_page.onboarding.onboard_5') %></p>
      <h4 class="fw-bold p-4 m-2 fs-2" style="color:#F07167"><%= t('landing_page.onboarding.onboard_6') %></h6>
    </div>
  </div>
</section>
<section>
  <div class="d-flex align-items-center text-center justify-content-center">
    <h3 class="fw-semibold text fs-6 mb-4 align-self-center" style="color:#11A87B;"><%= t('landing_page.popular') %></h3>
  </div>
  <div class="mt-4 mb-4 p-4 d-flex flex-column flex-md-row justify-content-around">
    <% @stores = Store.all.sample(3).each do |store| %>
      <div class="card m-1 d-flex flex-column align-items-center justify-content-center" >
        <div class="p-2 d-flex flex-column align-items-center justify-content-center">
          <div class="">
            <% if store.url %>
              <%= image_tag store.url, style:"max-width:10rem", id: "header-item-2" %>
            <% end %>
          </div>
          <div class="col-md-8">
            <div class="card-body p-4">
              <h5 class="card-title"><%= store.name%></h5>
              <p class="card-text"><%= store.foods.sample(3).map(&:name).join(", ") %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
</section>
<section>
  <div class="d-flex flex-column ">
    <h3 class="fw-semibold text fs-6 mb-4 align-self-center" style="color:#11A87B;"><%= t('landing_page.pitch.one')%></h3>
    <div class="d-flex flex-column flex-md-row justify-content-evenly">
      <div class="d-flex flex-column align-items-center justify-content-center m-4 p-2">
        <div class="d-flex align-items-center justify-content-center" style="width:100px;height: 100px;border-radius: 100px;background: #F07167"><i class="bi bi-patch-check" style="font-size: 2rem;color: white;"></i></div>
        <h4 class="fw-bold m-2"><%= t('landing_page.pitch.two')%></h4>
        <p><%= t('landing_page.pitch.two_subtext')%></p>
      </div>
      <div class="d-flex flex-column align-items-center justify-content-center m-4 p-2">
        <div class="d-flex align-items-center justify-content-center" style="width:100px;height: 100px;border-radius: 100px;background: #F07167"><i class="bi bi-shop" style="font-size: 2rem;color: white;"></i> </div>
        <h4 class="fw-bold m-2"><%= t('landing_page.pitch.three')%></h4>
        <p><%= t('landing_page.pitch.three_subtext')%></p>
      </div>
      <div class="d-flex flex-column align-items-center justify-content-center m-4 p-2">
        <div class="d-flex align-items-center justify-content-center" style="width:100px;height: 100px;border-radius: 100px;background: #F07167;"><i class="bi bi-card-checklist" style="font-size: 2rem;color: white;"></i></div>
        <h4 class="fw-bold m-2"><%= t('landing_page.pitch.four')%></h4>
        <p><%= t('landing_page.pitch.four_subtext')%></p>
      </div>
    </div>
  </div>
</section>
<section>
  <div class="w-100 h-75" id="burguer-container">
    <img src="/assets/landing-burguer.png" class="w-100 h-100 mb-4">
  </div>
</section>
<section>
  <div class="d-flex flex-column align-items-center justify-content-evenly" >
    <div class="d-flex justify-content-evenly align-items-center m-4 w-100" style="height:300px">
      <p class="d-flex flex-column p-2 text-center " style="color:#0081A7"><span class="fw-bolder text fs-1">+10000 </span><%= t('landing_page.numbers.delivered_orders')%></p>
      <p class="d-flex flex-column p-2 text-center" style="color:#0081A7"><span class="fw-bolder text fs-1">+150 </span><%= t('landing_page.numbers.partnered_restaurants')%></p>
      <p class="d-flex flex-column p-2 text-center" style="color:#0081A7"><span class="fw-bolder text fs-1"> 13 </span><%= t('landing_page.numbers.countries_reached')%></p>
    </div>
  </div>
</section>
<style >
  #img{
    border-radius: 20px;
    padding: 2re;
  }

  #burguer-container{
    overflow: hidden;
    max-height: 700px;
    margin-top: 20px;
  }

  h1{
    font-size: 3rem;
    margin-bottom: 2rem;
  }
</style>

app/views/static_pages/success.html.erb
<section>
  <div class="d-flex flex-column align-items-center justify-content-center p-4">

      <h2  class="fw-bold text-dark "><%= t('success.congratulations') %></h2>
        <h3 class="fw-semibold text-dark "><span></span><%= t('success.confirmed')%></h3>
        
        <img src="/assets/logo-md-transp.png">
        <h5 class="text-secondary text-md-start text"><%= t('success.preparing')%></h5>
        <p class="fw-semibold fw-4 p-2"> <i class="bi bi-bicycle text fs-4 p-2"></i><%= t('success.estimated')%></p>

        <div class="m-4" style="max-width:160px"><img src="/assets/pedido.png" class="img-fluid gif">
        </div>

  </div>

</section>

<style>
  .gif {
  animation-duration: 30s;
  animation-name: rotate;
}

@keyframes rotate {
  from {
    rotate: 0deg;
  }

  to {
    rotate: 360deg;
  }
}

</style>
  