config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'static_pages#landing'
    devise_for :users, :controllers => { registrations: 'users/registrations' }
    # Allows us to use link_to for session destroy
    devise_scope :user do
      get "/users/sign_out", as: "sign_out", to: "devise/sessions#destroy"
    end
    resources :stores, only: %i[index show]
    resources :locations, only: %i[index create]
    resource :shopping_cart, only: %i[show] do
      post 'add_food/:food_id(/:quantity)', action: :add_food, as: :add_food_to
      get 'checkout', action: :checkout, as: :checkout
      post 'remove_food/:food_id', action: :remove_food, as: :remove_food_from
    end
    resources :orders, only: %i[show] do
      post 'payment', action: :payment, as: :payment
    end
    # stripe webhooks
    mount StripeEvent::Engine, at: '/webhooks'
    post '/webhooks/stripe', to: 'webhooks#stripe'

    get "/success" => "static_pages#success"
  end
end

app/models/shopping_cart.rb
# == Schema Information
#
# Table name: shopping_carts
#
#  id          :bigint           not null, primary key
#  total_price :decimal(10, 2)   default(0.0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_shopping_carts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class ShoppingCart < ApplicationRecord
  belongs_to :user
  has_many :foods, through: :line_items
  has_many :line_items, dependent: :destroy
  has_one :order, dependent: :destroy

  def add_food(food, quantity = 1)
    current_item = line_items.find_by(food_id: food.id)
    if current_item
      current_item.quantity += quantity.to_i
      current_item.price = current_item.quantity * current_item.food.price
      
      current_item.save
    else
      current_item = line_items.build(food_id: food.id, quantity: quantity)
      current_item.price = current_item.quantity * current_item.food.price
      current_item.save
    end
    current_item
  end  
  def remove_food(food)
    current_item = line_items.find_by(food_id: food.id)
    if current_item.quantity > 1
      current_item.quantity -= 1
      current_item.price = current_item.quantity * current_item.food.price
      current_item.save
    else
      current_item.destroy
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.price }
  end

  def checkout
    user.orders.create(shopping_cart: self)
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
    before_action :authenticate_user!
    before_action :current_cart
  
    def show
      generate_mercadopago_preference_service = GenerateMercadopagoPreferenceService.new(@current_cart)
      @preference_id = generate_mercadopago_preference_service.call
      @current_cart
    end
  
    def add_food
      food = Food.find(params[:food_id])
      quantity = params[:quantity] || 1
      
      @current_cart.add_food(food, quantity)
    end
  
    def checkout
      @current_cart.checkout
      redirect_to order_path(@current_cart.order, locale: I18n.locale)
    end

    def remove_food
      food = Food.find(params[:food_id])
      @current_cart.remove_food(food)
      redirect_to shopping_cart_path
    end
    private
    def current_cart
      if session[:shopping_cart_id]
        shopping_cart = ShoppingCart.find_by(:id => session[:shopping_cart_id])
        if shopping_cart.present?
          @current_cart = shopping_cart
        else
          session[:shopping_cart_id] = nil
        end
      end

      if session[:shopping_cart_id] == nil
        @current_cart = ShoppingCart.create!(user: current_user)
        session[:shopping_cart_id] = @current_cart.id
      end
    end 
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/views/shopping_carts/_form.html.erb
<%= form_tag add_food_to_shopping_cart_path(food_id: @food.id), method: :post do %>
  <%= label_tag :quantity, "Quantity:" %>
  <%= number_field_tag :quantity, 1, min: 1 %>
  <%= submit_tag "Add to cart" %>
<% end %>
<%= form_tag remove_food_from_shopping_cart_path(food_id: @food.id), method: :post do %>
  <%= label_tag :quantity, "Quantity:" %>
  <%= number_field_tag :quantity, 1, min: 1 %>
  <%= submit_tag "Remove from cart" %>
<% end %>

app/views/shopping_carts/show.html.erb
<section>
  <div class="p-4 m-4">
    <h2 class="fw-bold fs-1"><%= t('order.your_order')%></h2>
    <div class="d-flex flex-column">
      <div class="accordion" id="accordionExample">
        <% @current_cart.line_items.group_by{ |item| item.food.store }.each do |store, items| %>
          <div class="accordion-item">
            <h2 class="accordion-header" id="heading<%= store.id %>">
              <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= store.id %>" aria-expanded="true" aria-controls="collapse<%= store.id %>">
                <%= store.name %>
              </button>
            </h2>
            <div id="collapse<%= store.id %>" class="accordion-collapse collapse show" aria-labelledby="heading<%= store.id %>" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                <% items.each do |item| %>
                  <div class="text fs-4 d-flex "><%= item.food.name %> </div>
                  <div class="d-flex justify-content-between w-50">
                    <p class="text-secondary"><%= t('order.unit_price')%> </p>
                    <%= number_to_currency(item.food.price) %></div>
                  <div class="d-flex justify-content-between w-50">
                    <p class="text-secondary"><%= t('order.quantity') %> </p>
                    <%= item.quantity %></div>
                  <div class="fw-bold d-flex justify-content-between w-50" style="color:#F07167">
                    <p><%= t('order.subtotal') %> </p>
                    <%= number_to_currency(item.food.price * item.quantity) %></div>
                  <div style="margin-bottom:4rem">
                    <%= form_with(url: remove_food_from_shopping_cart_path(item.food.id, locale: I18n.locale), method: :post) do |form| %>
                      <%= form.number_field :quantity, value: 1, min: 1,style:"max-width:40px" %>
                      <%= form.submit t('food.remove'),class:"btn btn-dark btn-sm text-light" %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="d-flex flex-column flex-md-row justify-content-between w-75" style="margin-top:2rem">
        <h6 class="fw-bold text fs-2 text"style="color:#11A87B"><%=t('order.total')%></h6>
        <div class="fw-bold text fs-2"><%= number_to_currency(@current_cart.total_price) %></div>
        <button class="btn btn-dark pagar"><%= link_to t('order.pay'), checkout_shopping_cart_path, method: :post, class:"text-light text-decoration-none" %>
        </button>
      </div>
    </div>
  </div>
</section>
<style>
  .pagar {
     padding-left: 4rem;
    padding-right: 4rem;
  }

  .pagar:hover{
    transform: scale(1.05);
    transition: 0.3s;
    padding-left: 4rem;
    padding-right: 4rem;
    background-color:#11A87B;
  }
</style>