config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'static_pages#landing'
    devise_for :users, :controllers => { registrations: 'users/registrations' }
    # Allows us to use link_to for session destroy
    devise_scope :user do
      get "/users/sign_out", as: "sign_out", to: "devise/sessions#destroy"
    end
    resources :stores, only: %i[index show]
    resources :locations, only: %i[index create]
    resource :shopping_cart, only: %i[show] do
      post 'add_food/:food_id(/:quantity)', action: :add_food, as: :add_food_to
      get 'checkout', action: :checkout, as: :checkout
      post 'remove_food/:food_id', action: :remove_food, as: :remove_food_from
    end
    resources :orders, only: %i[show] do
      post 'payment', action: :payment, as: :payment
    end
    # stripe webhooks
    mount StripeEvent::Engine, at: '/webhooks'
    post '/webhooks/stripe', to: 'webhooks#stripe'

    get "/success" => "static_pages#success"
  end
end

app/models/store.rb
# == Schema Information
#
# Table name: stores
#
#  id          :bigint           not null, primary key
#  average     :float
#  description :string
#  name        :string           not null
#  ratings     :float            default([]), is an Array
#  url         :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint
#
# Indexes
#
#  index_stores_on_category_id  (category_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#
class Store < ApplicationRecord
    belongs_to :category
    has_one :location , dependent: :destroy
    has_many :foods, dependent: :destroy
    has_one_attached :image
    before_save :update_average
    scope :filter_by_ratings, ->(ratings) { where('average >= ?', ratings )}
    scope :filter_by_search, ->(search) {where("stores.name ILIKE :search OR foods.name ILIKE :search", search: "#{search}%")}
    scope :filter_by_category, ->(category_id) {where("category_id = ?", category_id)}

    def update_average
        avg = 0
        self.ratings.each { |x| avg += x }
        self.average = avg/self.ratings.length
    end
end
  

app/controllers/stores_controller.rb
class StoresController < ApplicationController
    before_action :set_store, only: %i[show]

    def index
        @stores = Store.all
        @categories = Category.all

        if params[:near].present?
            if params[:near] == "true"
                @stores = distance_order(Location.find(current_user.location_id).street)
            end
        end
        @stores = @stores.includes(:foods).where("stores.name ILIKE :search OR foods.name ILIKE :search", search: "%#{params[:search]}%").references(:foods) if params[:search].present?
        @stores = @stores.filter_by_category(params[:category_id]) if params[:category_id].present?
        @stores = @stores.order(average: :desc) if params[:ratings].present?
    end
    
    def show 

        @latitude = @store.location.latitude
        @longitude = @store.location.longitude

    end

    # Al pasar un objeto de Location nos devuelve los locales dentro del radio especificado
    def distance_order(location) 
        near = Location.near(location,999).where("store_id IS NOT NULL")
        stores = Store.includes(:location).references(:location).merge(near)
        ids = []
        stores.each do |ele|
            ids << ele.id
        end
        @stores = Store.where(id: ids).in_order_of(:id, ids)
    end

    private
    
    def set_store
        @store = Store.find(params[:id])
    rescue ActiveRecord::RecordNotFound
        render json: { error: "Could not find any store with ID '#{params[:id]}'" }
    end

    def stores_params
        params.require(:store).permit(:search)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
    def make_params(url, new_param)
        # NO BORRAR, se utilizara a futuro
        
        # http://localhost:3000/stores#index
        # http://localhost:3000/stores?category_id=2
        # http://localhost:3000/stores?category_id=2&ratings=true
        # http://localhost:3000/stores?search=f&commit=Search&ratings=true&category_id=2
        # http://localhost:3000/stores?category_id=1
        url_split = url.split("stores") # => ?category_id=2&ratings=true
        new_param_split = new_param.split("=") # => ["ratings","true"]
        param = new_param_split[0].to_s # => ["ratings"]
        replace = ""
        if url_split.size == 1 # no tiene params
            url + "?" + new_param # concatenamos new param
        else
            url_params = url_split[1].split(/([?&])\w+/) #sub array de parametros ej: ["category_id=2",ratings=true]
            url_params.each_with_index do |sub_array, i| # => "category_id=2"
                if sub_array[new_param] # => encontro category_id en actual params
                    replace = sub_array # => texto a remplazar
                end
            end 
            if replace.empty?
                url + "&" + new_param
            else
                url.gsub(replace, new_param)
            end        
        end 
    end


    # <%= link_to "Puntuación" , make_params(request.original_url,"ratings=true"), class: "dropdown-item"%> 
    # <%= link_to "Más cercano" , make_params(request.original_url,"near=true"), class: "dropdown-item"%> 
    # <%= link_to category.name, make_params(request.original_url, "category_id=" + category.id.to_s), class: "dropdown-item"%> 
       
end

app/views/stores/_store.html.erb
<section> 

  <h4 class="fw-bold text-success text-center text-md-start m-md-4" style="margin-top: 2rem;"><%= t('store.restaurants')%></h4>
  
  <div class="d-flex flex-column flex-md-row flex-wrap m-4 p-4 align-items-center justify-content-center">
    <% @stores.each do |store| %>

      <div class="card m-4 card-local d-flex align-items-center justify-content-center" style="height:300px;width:200px" >
        <div class="card-body d-flex flex-column align-items-center justify-content-evenly ">
          <%= image_tag store.url, class: "img-fluid" %>
          <h5 class="card-title fw-bold"><%= store.name%></h5>
          <p class="card-title text fs-6">
            <%= store.average&.round(1) %>
            <i class="bi bi-star-fill" style="color:#F7B801"></i>
          </p>
          <%= link_to t('store.show_store'), store_path(id: store.id, locale: I18n.locale), class:"btn btn-success text-decoration-none", style:"background-color:#0081A7"%>
        </div>
      </div>

    <% end %>

  </div>
</section>

<style>
  
.card-local:hover{

  transform: scale(1.1);
  transition: 0.3s;
  -webkit-box-shadow: 10px -2px 108px -19px rgba(0,0,0,0.28);
  -moz-box-shadow: 10px -2px 108px -19px rgba(0,0,0,0.28);
  box-shadow: 10px -2px 108px -19px rgba(0,0,0,0.28);

}

</style>

app/views/stores/index.html.erb
<div class="bd-highlight d-flex flex-row flex-wrap p-4" id="landing-rectangle-body">

        <div class="dropdown-center p-1">
          <button class="btn btn-outline-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" style="background-color:#F07167">
            <%= t('store.sort_by')%>
          </button>
          <ul class="dropdown-menu ">
            <li class="dropdown-item">
              <% if params[:search].present? || params[:category_id].present? || params[:near].present? || params[:ratings].present?%>
                <% if params[:near].present? %>
                  <%= link_to t('store.score'),request.original_url.gsub("near=true", "ratings=true"), class: "dropdown-item"%>
                <% elsif params[:ratings].present? %> <%# si ya tiene el param rating, devuelve lo mismo%>
                  <%= link_to t('store.score'),request.original_url, class: "dropdown-item"%>
                <%else%><%# si NO  tiene el param rating, lo agrega%>
                  <%= link_to t('store.score'), request.original_url + "&ratings=true", class: "dropdown-item"%>    
                <%end%>
              <%else %>
                <%= link_to t('store.score'), request.original_url + "?ratings=true", class: "dropdown-item" %>
              <%end%>
            </li> 
            <li class="dropdown-item">
              <% if params[:search].present? || params[:category_id].present? || params[:near].present? || params[:ratings].present?%>
                  <% if params[:ratings].present? %>
                    <%= link_to t('store.nearest'),request.original_url.gsub("ratings=true", "near=true"), class: "dropdown-item"%>
                  <% elsif params[:near].present? %>
                    <%= link_to t('store.nearest'),request.original_url, class: "dropdown-item"%>
                  <%else%>
                    <%= link_to t('store.nearest'), request.original_url + "&near=true" , class: "dropdown-item"  %>
                  <%end%>
              <%else %>
                <%= link_to t('store.nearest'), request.original_url + "?near=true" , class: "dropdown-item"%>
              <%end%>  
            </li>
          </ul>
        </div>
     
      <div class="dropdown-center p-1">
        <button class="btn btn-outline-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" style="background-color:#F07167">
          <%= t('store.filter_by')%>
        </button>
        <ul class="dropdown-menu">
          <li><h6 class="dropdown-header"><%= t('store.categories') %></h6></li>
        <% @categories.each do |category| %>
          <li><% if params[:search].present? || params[:ratings].present? || params[:near].present?%>
                <%if params[:category_id].present? %> <%#si tiene param de categoria lo reemplza%>
                  <li><%= link_to category.name ,request.original_url.gsub("=#{params[:category_id]}", "=#{category.id}"), class: "dropdown-item"%></a> 
                <%else%> <%#si no tiene param de categoria lo agrega%>
                  <li><%= link_to category.name ,request.original_url + "&category_id=#{category.id}" , class: "dropdown-item" %></a>
                <%end%>
            <%else%>
              <li><%= link_to category.name , "stores?category_id=#{category.id}" , class: "dropdown-item"%></a>
            <%end%></li>
        <%end%>
        </ul>
      </div>

      
    </div>
    <% if params[:search].present? || params[:category_id].present? || params[:near].present? || params[:ratings].present?%>
        <button class="btn btn-outline-light" type="button" style="background-color:#F07167 ; margin-left:30px">
          <%= link_to t('store.clear_filters') , stores_path, class: "text-decoration-none text-white"%> <i class="bi bi-x"></i>

        </button>
    <%end%>

    <%= render 'store' %>

<style >
  
  .filtro{
    background-color: ;
  }
</style>

app/views/stores/show.html.erb
<section>
  <div class="container-fluid bg-dark bg-gradient p-4  " id="local-header" style="height: 14rem;">
    <h2 class="fw-bold" style="color:whitesmoke;"><%=@store.name%></h2>
    <p class="fw-semibold" style="color:whitesmoke;"><%=@store.average&.round(1)%>
      <i class="bi bi-star-fill" style="color:#F7B801"></i>
      <%= link_to t('cart.end_order'), shopping_cart_path,class:"btn btn-success text-decoration-none btn-lg", style:"float: right;"%>
    </p>
    <p class="fw-semibold" style="color:whitesmoke;">
      <%=@store.location.street%>
    </p>
    <p style="color:whitesmoke;"><%= t('cart.shipping_cost') %></p>
  </div>

  <div class="p-4">
    <h3><%= t('cart.popular') %></h3>
    <div class="d-flex flex-column-reverse flex-md-row"> 
      <div class="d-flex justify-content-start align-content-center flex-column flex-md-row m-4 flex-wrap">
        <% @store.foods.each do |food| %>
          <div class="card p-2 m-2 " style="max-width: 200px;">
            <div class="h-50" style="max-width:200px">
              <%= image_tag food.url, class: "img-fluid" %>
            </div>
            <div class="card-body">
              <h4><%=food.name%></h4>
              <p><%= t('food.description')%></p>
              <p class="fw-bold fs-6" style="color:#F07167">$<%= food.price %></p>
                <%= form_with(url: add_food_to_shopping_cart_path(food.id, locale: I18n.locale), method: :post) do |form| %>
                <%= form.number_field :quantity, value: 1, min: 1, max: 10, class: "form-control mb-3 w-50" %>
                <%= form.submit t('food.add'), class: "btn btn-success btn-sm" %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <div>
        <h5><%= t('store.location') %></h5>
        <%= js_map [{
                latitude: @latitude,
                longitude: @longitude,
                label: @store.name
                }],
                id: "cities-map",
                width: "20rem",
                height: "20rem",
                markers: {color: "#11a87b"},
                tooltips: { hover: false, html: true},
                style: "mapbox://styles/mapbox/outdoors-v12",
                zoom: 15,
                controls: true,
                refresh: 60 %>
      </div>
    </div>
  </section>