config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'static_pages#landing'
    devise_for :users, :controllers => { registrations: 'users/registrations' }
    # Allows us to use link_to for session destroy
    devise_scope :user do
      get "/users/sign_out", as: "sign_out", to: "devise/sessions#destroy"
    end
    resources :stores, only: %i[index show]
    resources :locations, only: %i[index create]
    resource :shopping_cart, only: %i[show] do
      post 'add_food/:food_id(/:quantity)', action: :add_food, as: :add_food_to
      get 'checkout', action: :checkout, as: :checkout
      post 'remove_food/:food_id', action: :remove_food, as: :remove_food_from
    end
    resources :orders, only: %i[show] do
      post 'payment', action: :payment, as: :payment
    end
    # stripe webhooks
    mount StripeEvent::Engine, at: '/webhooks'
    post '/webhooks/stripe', to: 'webhooks#stripe'

    get "/success" => "static_pages#success"
  end
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id               :bigint           not null, primary key
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  shopping_cart_id :bigint           not null
#  user_id          :bigint           not null
#
# Indexes
#
#  index_orders_on_shopping_cart_id  (shopping_cart_id)
#  index_orders_on_user_id           (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (shopping_cart_id => shopping_carts.id)
#  fk_rails_...  (user_id => users.id)
#
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :shopping_cart
  has_many :line_items, through: :shopping_cart
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_order, only: [:show, :payment]
    def show
        generate_mercadopago_preference_service = GenerateMercadopagoPreferenceService.new(@order.shopping_cart)
        @preference_id = generate_mercadopago_preference_service.call  
        @order
    end

    def payment
        # I'm hardcoding the api_key because env vars and credentials are not working for me. I think it should be working in production env though.
        Stripe.api_key = "sk_test_51Mf4CQAgLOp41ZUX84T7CYR6yA8AkK9PLsrw9ZbNy1tZTdB5caRUoU14j3T9FKfnpSRCG9ZybAa63EuqHUkMNqV400MUqXpIyC"
        puts "stripe api key: #{Stripe.api_key}"
        #create prices array with the format [{price: price_id, quantity: quantity}]
        prices = []
        @order.line_items.each do |line_item|
            prices.push({price: line_item.food.stripe_price_id, quantity: line_item.quantity})
        end
        @order_session = Stripe::Checkout::Session.create(
            mode: 'payment',
            client_reference_id: @order.id,
            currency: 'usd',
            customer_email: current_user.email,
            # pass prices
            line_items: prices,
            client_reference_id: @order.id,
            payment_method_types: ['card'],
            success_url: success_url,
            cancel_url: root_url,
        )
        #redirect and empty cart
        redirect_to @order_session.url, status: 303, allow_other_host: true, target: "_blank"
    end
    
    private
    def set_order
        @order ||= current_user.orders.find(params[:id] || params[:order_id])
    end
end

app/views/orders/show.html.erb
<style>

  .mercadopago-button {
    /*dont craete newline*/
  white-space: nowrap;
  /* make font more thicker */
  font-weight: 600;
  }

  .size_button {
    width:218px;
    height:37px;
  }

</style>

<section class="p-4">

  <h2 class="fw-bold"><%= t('order.confirm')%></h1>
  <h4 class="fw-semibold"><%= t('order.resume')%></h3>

  <div>
    <div class="">
      <% @order.line_items.each do |item| %>
        <div class="d-flex flex-column">
          <div class="d-flex justify-content-between align-items-center"> 
            <p><%= item.food.name %> </p>   
            <p class="fw-semibold"><%= number_to_currency(item.food.price) %></p>   
            <p>x<%= item.quantity %></p>   
            <p class="fw-bold fs-5"><%= number_to_currency(item.food.price * item.quantity) %></p>   
          </div>    
        </div>
      <% end %> 
      <div class="d-flex justify-content-between">
        <p><%= t('order.shipping_cost_promotion')%></p> 
        <p class="fw-bold fs-5"> $0</p>
      </div>`
    </div>
  </div>

  <div class="bg-light p-2">
    <div class="d-flex justify-content-between">
      <h6 class="fw-bold fs-2" >Total</h6> 
      <div class="fw-bold fs-2"><%= number_to_currency(@order.line_items.to_a.sum { |item| item.food.price * item.quantity }) %></div>
    </div>      
    <p><%= t('payment.choice')%></p>
    <div class="form-check" >
      <div class="m-2">  
        <%= form_tag order_payment_path(@order, locale: I18n.locale), method: :post do %>
          <%= hidden_field_tag :order_id, @order.id %>
          <%= submit_tag t('payment.stripe'), class: "btn btn-primary btn-block size_button" %>
        <% end %>   
      </div>  <%# call post payment and pass @order.id params %>
                  
      <div class="checkout-btn m-2"></div>
          
      <div class="m-2">
        <button class="btn btn-primary btn-block size_button">
          <%= link_to t('payment.cash'), success_path , class:"nav-link active"%>
        </button>
      </div>
    </div>
  </div>

  <script src="https://sdk.mercadopago.com/js/v2"></script>
  <script>
    const mp = new MercadoPago('TEST-21a4a1ad-cddb-4363-9e9f-1a4c4ecc5d20', {
        locale: 'es-AR'
    })
    const checkout = mp.checkout({
        preference: {
            id: '<%= @preference_id %>'

        }

    });
    checkout.render({
        container: '.checkout-btn',
        label: '<%= t("payment.mercadopago") %>',
        class: 'btn btn-primary size_button',
    });
  </script>
</section>